import { Product } from "@/models";

export const mockProducts: Product[] = [
  {
    id: 1,
    name: "Product 1",
    category: "electronics",
    price: 100,
    gender: "unisex",
    size: "one size",
    colors: ["black", "white"],
    image: "/images/product1.jpg",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    brand: "Brand 1",
  },
  {
    id: 2,
    name: "Product 2",
    category: "electronics",
    price: 150,
    gender: "men",
    size: "M",
    colors: ["blue", "red"],
    image:
      "https://images.unsplash.com/photo-1627225924765-552d49cf47ad?q=80&w=3087&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    brand: "Brand 2",
  },
  {
    id: 3,
    name: "Product 3",
    category: "clothing",
    price: 50,
    gender: "woman",
    size: "S",
    colors: ["pink", "yellow"],
    image:
      "https://images.unsplash.com/flagged/photo-1556637640-2c80d3201be8?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8M3x8c25lYWtlcnxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60?a=b",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    brand: "Brand 3",
  },
  {
    id: 4,
    name: "Product 4",
    category: "clothing",
    price: 80,
    gender: "unisex",
    size: "L",
    colors: ["green", "purple"],
    image:
      "https://images.unsplash.com/flagged/photo-1556637640-2c80d3201be8?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8M3x8c25lYWtlcnxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60?a=b",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    brand: "Brand 4",
  },
  {
    id: 5,
    name: "Product 5",
    category: "electronics",
    price: 120,
    gender: "unisex",
    size: "one size",
    colors: ["silver", "gold"],
    image:
      "https://images.unsplash.com/flagged/photo-1556637640-2c80d3201be8?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8M3x8c25lYWtlcnxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60?a=b",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    brand: "Brand 5",
  },
  {
    id: 6,
    name: "Product 6",
    category: "electronics",
    price: 200,
    gender: "woman",
    size: "M",
    colors: ["pink", "white"],
    image:
      "https://images.unsplash.com/flagged/photo-1556637640-2c80d3201be8?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8M3x8c25lYWtlcnxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60?a=b",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    brand: "Brand 6",
  },
  {
    id: 7,
    name: "Product 7",
    category: "clothing",
    price: 70,
    gender: "men",
    size: "L",
    colors: ["blue", "black"],
    image:
      "https://images.unsplash.com/flagged/photo-1556637640-2c80d3201be8?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8M3x8c25lYWtlcnxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60?a=b",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    brand: "Brand 7",
  },
  {
    id: 8,
    name: "Product 8",
    category: "clothing",
    price: 90,
    gender: "unisex",
    size: "S",
    colors: ["green", "yellow"],
    image:
      "https://images.unsplash.com/flagged/photo-1556637640-2c80d3201be8?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8M3x8c25lYWtlcnxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60?a=b",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    brand: "Brand 8",
  },
  // Additional products to make a total of 20
  {
    id: 9,
    name: "Product 9",
    category: "shoes",
    price: 120,
    gender: "unisex",
    size: "42",
    colors: ["black", "white"],
    image: "/images/product9.jpg",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    brand: "Brand 9",
  },
  {
    id: 10,
    name: "Product 10",
    category: "shoes",
    price: 180,
    gender: "men",
    size: "44",
    colors: ["blue", "red"],
    image: "/images/product10.jpg",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    brand: "Brand 10",
  },
  {
    id: 11,
    name: "Product 11",
    category: "shoes",
    price: 80,
    gender: "woman",
    size: "39",
    colors: ["pink", "yellow"],
    image: "/images/product11.jpg",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    brand: "Brand 11",
  },
  {
    id: 12,
    name: "Product 12",
    category: "shoes",
    price: 150,
    gender: "unisex",
    size: "41",
    colors: ["green", "blue"],
    image: "/images/product12.jpg",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    brand: "Brand 12",
  },
  {
    id: 13,
    name: "Product 13",
    category: "shoes",
    price: 100,
    gender: "woman",
    size: "38",
    colors: ["pink", "white"],
    image: "/images/product13.jpg",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    brand: "Brand 13",
  },
  {
    id: 14,
    name: "Product 14",
    category: "shoes",
    price: 200,
    gender: "men",
    size: "45",
    colors: ["black", "red"],
    image:
      "https://images.unsplash.com/photo-1576566588028-4147f3842f27?q=80&w=2400&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    brand: "Brand 14",
  },
  {
    id: 15,
    name: "Product 15",
    category: "clothing",
    price: 80,
    gender: "unisex",
    size: "40",
    colors: ["blue", "green"],
    image: "/images/product15.jpg",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    brand: "Brand 15",
  },
  {
    id: 16,
    name: "Product 16",
    category: "clothing",
    price: 120,
    gender: "woman",
    size: "37",
    colors: ["white", "silver"],
    image: "/images/product16.jpg",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    brand: "Brand 16",
  },
  {
    id: 17,
    name: "Product 17",
    category: "bags",
    price: 90,
    gender: "men",
    size: "43",
    colors: ["black", "brown"],
    image: "/images/product17.jpg",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    brand: "Brand 17",
  },
  {
    id: 18,
    name: "Product 18",
    category: "shoes",
    price: 150,
    gender: "unisex",
    size: "39",
    colors: ["blue", "white"],
    image: "/images/product18.jpg",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    brand: "Brand 18",
  },
  {
    id: 19,
    name: "Product 19",
    category: "shoes",
    price: 70,
    gender: "woman",
    size: "36",
    colors: ["pink", "yellow"],
    image: "/images/product19.jpg",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    brand: "Brand 19",
  },
  {
    id: 20,
    name: "Product 20",
    category: "clothing",
    price: 110,
    gender: "unisex",
    size: "42",
    colors: ["black", "red"],
    image: "/images/product20.jpg",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    brand: "Brand 20",
  },
];
